// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/_middleware.ts";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/ws/index.ts";
import * as $$0 from "./islands/Board.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/_middleware.ts": $1,
    "./routes/index.tsx": $2,
    "./routes/ws/index.ts": $3,
  },
  islands: {
    "./islands/Board.tsx": $$0,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
